#!/usr/bin/env bash

set -exuo pipefail

here="$(dirname $0)"

. "$here/config.sh"

cd "$here/.."

if [ ! -e $(basename $repo_url) ]; then
	git clone "$repo_url"
fi
cd $(basename $repo_url)
git fetch
git checkout "$base_revision"
